const { DATA_DIR, ACCTS_DIR, IDX_PATH } = require("./config");
const {
  AccountCredentialError,
  setSecretCodec,
  protectData,
  unprotectData,
  ensureDir,
  normalizeAccountId,
  getStorageDiagnostics,
  encodeAccount,
  decodeAccount,
  loadAccountPath,
  accountSummary,
  flushPendingAccountRewrites,
  resetPendingAccountRewritesForTests,
  createAccountFileStore,
} = require("./account-file-store");

const store = createAccountFileStore({
  prefix: "codex_",
  accountsDir: ACCTS_DIR,
  indexPath: IDX_PATH,
  dataDir: DATA_DIR,
  currentField: "current_account_id",
  indexVersion: "2.0",
  preserveIndexExtras: true,
  useIndexBackup: true,
  quarantineUnreadableIndex: true,
  recordIndexDiagnostics: true,
  logIndexSync: true,
  eagerIndexLoad: true,
  normalizeOnLoad: true,
  saveForeignPrefixError: "Cursor accounts cannot be stored in the Codex account directory",
  allowDeleteIndexOption: true,
  deleteRollbackLabel: "Rollback failed",
  indexInvalidMessage: "Account index has an invalid structure",
  invalidIdError: "Invalid account id",
});

module.exports = {
  AccountCredentialError,
  setSecretCodec,
  protectData,
  unprotectData,
  ensureDir,
  normalizeAccountId,
  accountFilePath: store.accountFilePath,
  loadIdx: store.loadIdx,
  saveIdx: store.saveIdx,
  withIndexLock: store.withIndexLock,
  loadAcct: store.loadAcct,
  saveAcct: store.saveAcct,
  deleteAcct: store.deleteAcct,
  listAccts: store.listAccts,
  currentAcct: store.currentAcct,
  getStorageDiagnostics,
  rebuildIndex: store.rebuildIndex,
  encodeAccount,
  decodeAccount,
  loadAccountPath,
  accountSummary,
  flushPendingAccountRewrites,
  resetPendingAccountRewritesForTests,
};
